In [5]:
import os
import cv2
import numpy as np
from skimage.feature import hog

In [6]:
x=[] #image arrays
y=[] #class
dataset_path="archive/train"
emotions=os.listdir(dataset_path)
for label,class_name in enumerate(emotions):
    class_folder=os.path.join(dataset_path,class_name)
    for file in os.listdir(class_folder):
        img_path=os.path.join(class_folder,file)
        img=cv2.imread(img_path,cv2.IMREAD_GRAYSCALE)
        if img is None:
            continue
        img=cv2.resize(img,(48,48))
        features, _ = hog(img, orientations=9, pixels_per_cell=(8,8),
                          cells_per_block=(2,2), block_norm='L2-Hys',
                          visualize=True)
        x.append(features)
        y.append(label)
x=np.array(x)
y=np.array(y)
print(x.shape)
print(y.shape)
x=x/ np.max(x)
print(x[0:2,:])

(28709, 900)
(28709,)
[[0.16498825 0.06005869 0.13194382 ... 0.03975727 0.31720688 0.31720688]
 [0.180475   0.05400996 0.04686234 ... 0.09811713 0.07713442 0.05111089]]


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.decomposition import PCA


In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


In [ ]:
pca=PCA(n_components=400)
x_train=pca.fit_transform(x_train)
x_test=pca.fit_transform(x_test)


In [9]:
model = SVC(kernel='linear', probability=True)
model.fit(x_train, y_train)

SVC(kernel='linear', probability=True)

In [10]:
y_pred=model.predict(x_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.43660745384883315


In [11]:
x_train[0,:]

array([0.33595973, 0.33595973, 0.33595973, 0.11553907, 0.18952443,
       0.03295738, 0.00505543, 0.01361217, 0.08078134, 0.24111535,
       0.15863319, 0.17180204, 0.08583379, 0.04131966, 0.        ,
       0.01263858, 0.01199001, 0.05836033, 0.09690481, 0.33595973,
       0.22316602, 0.03640478, 0.06255777, 0.06742119, 0.02659835,
       0.00893682, 0.02743183, 0.03562079, 0.12699486, 0.04062593,
       0.33595973, 0.33595973, 0.21573923, 0.0330695 , 0.04727186,
       0.02563549, 0.25674848, 0.16891844, 0.18294112, 0.09139897,
       0.0439987 , 0.        , 0.01345802, 0.0127674 , 0.06214422,
       0.23792532, 0.15520849, 0.15412975, 0.04742674, 0.02294443,
       0.09041054, 0.05666415, 0.02912563, 0.0724764 , 0.03793032,
       0.13522879, 0.04325998, 0.3414337 , 0.3414337 , 0.22972706,
       0.03521362, 0.05033681, 0.02729761, 0.09643231, 0.04111268,
       0.        , 0.21096382, 0.3414337 , 0.3414337 , 0.3414337 ,
       0.08405944, 0.09236518, 0.30930786, 0.20177426, 0.20037